### ISSUE TITLE
3.0.1 dependencies are broken - java.lang.NoClassDefFoundError: org/jdom/Content

### ISSUE THREAD

**Issue by Woodz** [HalBuilder/halbuilder-xml#2]
3.0.1 dependencies state that they require any version of halbuilder-api from 3.0.0 upto but not including 4.0.0. However halbuilder-xml 3.0.1 does not work with halbuilder-api 3.1.2 as this now has removed the JDOM dependency, causing applications to now throw java.lang.NoClassDefFoundError: org/jdom/Content.

**Comment by talios** [comment]
Ack - I knew that might bite me.  `halbuilder-xml 3.0.2` was released at the same time which picked up the JDOM dependency.

Hate. Transitive. Dependencies.
